spring.application.name=task-queue

spring.datasource.url=jdbc:postgresql://localhost:5432/taskqueue
spring.datasource.username=postgres
spring.datasource.password=shree420
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
